import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';

import '../models/beneficiary.dart';
import '../models/user_profile.dart';

class HiveManager {
  // Box names
  static const String beneficiariesBox = "beneficiaries";
  static const String pendingQueueBox = "pending_queue";
  static const String dropdownCacheBox = "dropdown_cache";
  static const String userProfileBox = "user_profile";

  // -----------------------------
  // INIT HIVE
  // -----------------------------
  static Future<void> initHive() async {
    await Hive.initFlutter();

    // Register adapters (generated by build_runner)
    if (!Hive.isAdapterRegistered(1)) {
      Hive.registerAdapter(BeneficiaryAdapter());
    }
    if (!Hive.isAdapterRegistered(2)) {
      Hive.registerAdapter(UserProfileAdapter());
    }

    // -----------------------------
    // OPEN BOXES
    // -----------------------------
    await Hive.openBox<Beneficiary>(beneficiariesBox);
    await Hive.openBox<Map>(pendingQueueBox);
    await Hive.openBox(dropdownCacheBox);
    await Hive.openBox<UserProfile>(userProfileBox);
  }

  // -----------------------------
  // ACCESSORS
  // -----------------------------
  static Box<Beneficiary> get beneficiaries =>
      Hive.box<Beneficiary>(beneficiariesBox);

  static Box<Map> get queue => Hive.box<Map>(pendingQueueBox);

  static Box get dropdownCache => Hive.box(dropdownCacheBox);

  static Box<UserProfile> get userProfile =>
      Hive.box<UserProfile>(userProfileBox);

  // -----------------------------
  // CLEAR ALL DATA (debug use)
  // -----------------------------
  static Future<void> clearAll() async {
    await beneficiaries.clear();
    await queue.clear();
    await dropdownCache.clear();
    await userProfile.clear();
  }

  // -----------------------------
  // RESET SYNC FLAG
  // -----------------------------
  static void resetSyncState() {
    for (var b in beneficiaries.values) {
      b.synced = "no";
      b.save();
    }
  }

  // -----------------------------
  // ADD TO QUEUE
  // -----------------------------
  static Future<void> pushToQueue(Map payload) async {
    await queue.add(payload);
  }

  // -----------------------------
  // POP FIRST ITEM IN QUEUE
  // -----------------------------
  static Future<Map?> popQueue() async {
    if (queue.isEmpty) return null;

    final key = queue.keyAt(0);
    final item = queue.getAt(0);
    await queue.delete(key);
    return item;
  }
}
