# Generated by Django 5.2.4 on 2025-09-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=255, unique=True)),
                ('IP_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Sector', models.CharField(blank=True, max_length=255, null=True)),
                ('Indicator', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('ID_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_of_Birth', models.DateTimeField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=255, null=True)),
                ('Governorate', models.CharField(blank=True, max_length=255, null=True)),
                ('Municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('Neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('Site_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Disability_Status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
