# Generated by Django 5.2.4 on 2025-09-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_alter_beneficiary_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='Age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
