# Generated by Django 5.2.4 on 2025-10-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_beneficiary_instanceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='Deleted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='Parent_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='Spouse_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
