# Generated by Django 5.2.4 on 2025-10-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0013_alter_beneficiary_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='Household_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
