# Generated by Django 5.2.4 on 2025-09-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_beneficiary_delete_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='Date_of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
