# Generated by Django 5.2.4 on 2025-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_beneficiary_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='InForm_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
