# Generated by Django 5.2.4 on 2025-09-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_beneficiary_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='IP',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='section',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
