# Generated by Django 5.2.4 on 2025-10-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_apitoken_ip_alter_apitoken_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='InstanceID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
