# Generated by Django 5.2.4 on 2025-10-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0017_beneficiary_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='Deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
