# Generated by Django 5.2.4 on 2025-10-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0018_alter_beneficiary_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='undeleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
