# Generated by Django 5.2.4 on 2025-10-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0019_beneficiary_undeleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='record_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
