# Generated by Django 5.2.8 on 2025-12-01 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0020_alter_beneficiary_record_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'permissions': [('import_beneficiary', 'Can import beneficiary'), ('export_beneficiary', 'Can export beneficiary')]},
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
