# Generated by Django 5.2.8 on 2025-12-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0021_alter_beneficiary_options_beneficiary_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='synced',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
