# Generated by Django 5.2.8 on 2025-12-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0022_beneficiary_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
