# Generated by Django 5.2.8 on 2025-12-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0023_alter_beneficiary_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
