# Generated by Django 5.2.8 on 2025-12-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0024_beneficiary_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='undeleted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
