# Generated by Django 5.2.8 on 2025-12-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0025_beneficiary_deleted_by_beneficiary_undeleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='updated_by',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
