# Generated by Django 5.2.8 on 2025-12-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0026_beneficiary_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='Benefit_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='Eligiblity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='HH_Members',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='Marital_Status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='Type_of_Supply',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
