# Generated by Django 5.2.8 on 2025-12-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0027_beneficiary_benefit_date_beneficiary_eligiblity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=255, null=True)),
                ('IP_Name', models.CharField(max_length=255, null=True)),
                ('Type_of_Supply', models.CharField(max_length=255)),
                ('Eligibilioty_Time', models.CharField(max_length=500)),
                ('Distripution_Date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
