# Generated by Django 5.2.8 on 2025-12-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0028_supply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='Eligibilioty_Time',
            new_name='Eligibilioty_Period',
        ),
    ]
