# Generated by Django 5.2.8 on 2025-12-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0029_rename_eligibilioty_time_supply_eligibilioty_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='Eligibilioty_Period',
            new_name='eligibility_period',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='Type_of_Supply',
            new_name='supply_type',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='Distripution_Date',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='IP_Name',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='Section',
        ),
        migrations.AddField(
            model_name='supply',
            name='distribution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='ip_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
