# Generated by Django 5.2.8 on 2025-12-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0030_rename_eligibilioty_period_supply_eligibility_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='Type_of_Supply',
            new_name='Supply_Type',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='myproject.supply'),
        ),
    ]
