# Generated by Django 5.2.8 on 2025-12-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0031_rename_type_of_supply_beneficiary_supply_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='Eligiblity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
