# Generated by Django 5.2.8 on 2025-12-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0032_alter_beneficiary_eligiblity'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='Override_At',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='Override_By',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='Override_Eligibility',
            field=models.BooleanField(default=False),
        ),
    ]
