# Generated by Django 5.2.8 on 2025-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0033_beneficiary_override_at_beneficiary_override_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='supply_batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
