# Generated by Django 5.2.8 on 2025-12-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0034_beneficiary_supply_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
