# Generated by Django 5.2.4 on 2025-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_submission_created_at_alter_submission_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
