# Generated by Django 5.2.4 on 2025-09-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_beneficiary_inform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='Submission_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
