# Generated by Django 5.2.4 on 2025-10-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_beneficiary_household_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='household',
        ),
        migrations.DeleteModel(
            name='Household',
        ),
    ]
