# Generated by Django 5.2.4 on 2025-10-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0015_remove_beneficiary_household_delete_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
    ]
