# Generated by Django 5.2.4 on 2025-10-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0016_alter_beneficiary_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
