# Generated by Django 5.2.8 on 2025-11-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='new_data',
            new_name='changes',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='old_data',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='record_id',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
