# Generated by Django 5.2.8 on 2025-11-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_rename_new_data_auditlog_changes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='object_id',
            new_name='app_name',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='changes',
            new_name='new_data',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='record_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
