# Generated by Django 5.2.8 on 2025-11-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_rename_object_id_auditlog_app_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='new_data',
            new_name='changes',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='app_name',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='old_data',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='record_id',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
