# Generated by Django 5.2.8 on 2025-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_rename_new_data_auditlog_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
