# Generated by Django 5.2.8 on 2025-12-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auditlog_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='object_id',
            new_name='record_id',
        ),
    ]
